"""add reflection log, procedural strategies, last_reinforced_at

Revision ID: b2823b78b8c5
Revises: 33c4fd27a9e9
Create Date: 2026-07-09 13:58:15.763478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2823b78b8c5'
down_revision: Union[str, Sequence[str], None] = '33c4fd27a9e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedural_strategies',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('strategy_name', sa.String(length=32), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('successes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'strategy_name')
    )
    op.create_table('reflection_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('fact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reflection_log_user', 'reflection_log', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reflection_log_user_id'), 'reflection_log', ['user_id'], unique=False)
    op.add_column('semantic_memories', sa.Column('last_reinforced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semantic_memories', 'last_reinforced_at')
    op.drop_index(op.f('ix_reflection_log_user_id'), table_name='reflection_log')
    op.drop_index('ix_reflection_log_user', table_name='reflection_log')
    op.drop_table('reflection_log')
    op.drop_table('procedural_strategies')
    # ### end Alembic commands ###
